/**
 * @type {import('ioredis').RedisOptions} Options
 */
module.exports.redisConfig = {
  port: 6379,
  host: 'redis-server'
}

/**
 * @type {import('./src/types').User}
 */
module.exports.firstUser = {
  username: 'admin',
  email: 'admin@localhost',
  password: 'password',
  id: 0,
  permissions: 511 // All permissions
}

module.exports.RESOURCES_AVAILABLE = [
  {
    "value": "Mentorship Programs",
    "label": "Mentorship Programs"
  },
  {
    "value": "Internship Opportunities",
    "label": "Internship Opportunities"
  },
  {
    "value": "Scholarships and Grants",
    "label": "Scholarships and Grants"
  },
  {
    "value": "Technology Access",
    "label": "Technology Access"
  },
  {
    "value": "Guest Lectures and Workshops",
    "label": "Guest Lectures and Workshops"
  },
  {
    "value": "Art and Music Supplies",
    "label": "Art and Music Supplies"
  },
  {
    "value": "Sports Equipment and Facilities",
    "label": "Sports Equipment and Facilities"
  },
  {
    "value": "Science and Lab Equipment",
    "label": "Science and Lab Equipment"
  },
  {
    "value": "Library Resources",
    "label": "Library Resources"
  },
  {
    "value": "Extracurricular Program Sponsorship",
    "label": "Extracurricular Program Sponsorship"
  }
]

module.exports.firstPartners = [
  {
    "partnerName": "Partner 5719",
    "organizationType": "Educational Institution",
    "resourcesAvailable": "Sports Equipment and Facilities, Scholarships and Grants",
    "contactName": "Contact 8045",
    "contactEmail": "contact3483@partner.com",
    "contactPhone": "834-969-2128",
    "addressStreet": "2693 Main St",
    "addressCity": "City 487",
    "addressState": "VA",
    "addressZipCode": "56773",
    "website": "http://www.partner7884.com",
    "description": "Description of Partner 6163",
    "partnershipStatus": "1"
  },
  {
    "partnerName": "Partner 9859",
    "organizationType": "Startup",
    "resourcesAvailable": "Mentorship Programs, Art and Music Supplies",
    "contactName": "Contact 452",
    "contactEmail": "contact375@partner.com",
    "contactPhone": "896-422-3826",
    "addressStreet": "1766 Main St",
    "addressCity": "City 598",
    "addressState": "PA",
    "addressZipCode": "64997",
    "website": "http://www.partner2894.com",
    "description": "Description of Partner 7065",
    "partnershipStatus": "1"
  },
  {
    "partnerName": "Partner 444",
    "organizationType": "NGO",
    "resourcesAvailable": "Science and Lab Equipment, Library Resources",
    "contactName": "Contact 3501",
    "contactEmail": "contact1727@partner.com",
    "contactPhone": "892-495-5316",
    "addressStreet": "1053 Main St",
    "addressCity": "City 307",
    "addressState": "IL",
    "addressZipCode": "78885",
    "website": "http://www.partner6538.com",
    "description": "Description of Partner 5733",
    "partnershipStatus": "1"
  },
  {
    "partnerName": "Partner 6959",
    "organizationType": "NGO",
    "resourcesAvailable": "Sports Equipment and Facilities, Science and Lab Equipment",
    "contactName": "Contact 1261",
    "contactEmail": "contact280@partner.com",
    "contactPhone": "235-537-7476",
    "addressStreet": "6463 Main St",
    "addressCity": "City 86",
    "addressState": "OH",
    "addressZipCode": "25018",
    "website": "http://www.partner9929.com",
    "description": "Description of Partner 8437",
    "partnershipStatus": "1"
  },
  {
    "partnerName": "Partner 7589",
    "organizationType": "Corporation",
    "resourcesAvailable": "Mentorship Programs, Sports Equipment and Facilities, Scholarships and Grants",
    "contactName": "Contact 3877",
    "contactEmail": "contact7946@partner.com",
    "contactPhone": "398-793-9703",
    "addressStreet": "9251 Main St",
    "addressCity": "City 513",
    "addressState": "IL",
    "addressZipCode": "73796",
    "website": "http://www.partner4069.com",
    "description": "Description of Partner 5974",
    "partnershipStatus": "1"
  },
  {
    "partnerName": "Partner 6427",
    "organizationType": "Non-Profit",
    "resourcesAvailable": "Mentorship Programs, Guest Lectures and Workshops, Scholarships and Grants, Science and Lab Equipment, Internship Opportunities",
    "contactName": "Contact 8181",
    "contactEmail": "contact5227@partner.com",
    "contactPhone": "869-695-7733",
    "addressStreet": "332 Main St",
    "addressCity": "City 95",
    "addressState": "CA",
    "addressZipCode": "82659",
    "website": "http://www.partner4544.com",
    "description": "Description of Partner 3824",
    "partnershipStatus": "1"
  },
  {
    "partnerName": "Partner 3008",
    "organizationType": "Corporation",
    "resourcesAvailable": "Scholarships and Grants",
    "contactName": "Contact 4869",
    "contactEmail": "contact200@partner.com",
    "contactPhone": "318-204-6172",
    "addressStreet": "5689 Main St",
    "addressCity": "City 205",
    "addressState": "MA",
    "addressZipCode": "50589",
    "website": "http://www.partner1589.com",
    "description": "Description of Partner 5735",
    "partnershipStatus": "1"
  },
  {
    "partnerName": "Partner 9524",
    "organizationType": "Educational Institution",
    "resourcesAvailable": "Internship Opportunities, Art and Music Supplies",
    "contactName": "Contact 8569",
    "contactEmail": "contact5140@partner.com",
    "contactPhone": "406-626-1550",
    "addressStreet": "81 Main St",
    "addressCity": "City 638",
    "addressState": "VA",
    "addressZipCode": "35147",
    "website": "http://www.partner4674.com",
    "description": "Description of Partner 1081",
    "partnershipStatus": "1"
  },
  {
    "partnerName": "Partner 3329",
    "organizationType": "Startup",
    "resourcesAvailable": "Scholarships and Grants",
    "contactName": "Contact 2454",
    "contactEmail": "contact3197@partner.com",
    "contactPhone": "263-136-3822",
    "addressStreet": "7791 Main St",
    "addressCity": "City 192",
    "addressState": "PA",
    "addressZipCode": "61898",
    "website": "http://www.partner9117.com",
    "description": "Description of Partner 3829",
    "partnershipStatus": "1"
  },
  {
    "partnerName": "Partner 2547",
    "organizationType": "Government Agency",
    "resourcesAvailable": "Technology Access, Sports Equipment and Facilities, Science and Lab Equipment, Internship Opportunities",
    "contactName": "Contact 1228",
    "contactEmail": "contact8084@partner.com",
    "contactPhone": "745-976-3298",
    "addressStreet": "323 Main St",
    "addressCity": "City 482",
    "addressState": "MA",
    "addressZipCode": "51958",
    "website": "http://www.partner2399.com",
    "description": "Description of Partner 7201",
    "partnershipStatus": "1"
  },
  {
    "partnerName": "Partner 9492",
    "organizationType": "Corporation",
    "resourcesAvailable": "Extracurricular Program Sponsorship",
    "contactName": "Contact 3792",
    "contactEmail": "contact3089@partner.com",
    "contactPhone": "469-787-2435",
    "addressStreet": "7844 Main St",
    "addressCity": "City 542",
    "addressState": "CA",
    "addressZipCode": "28019",
    "website": "http://www.partner9273.com",
    "description": "Description of Partner 146",
    "partnershipStatus": "1"
  },
  {
    "partnerName": "Partner 8011",
    "organizationType": "Startup",
    "resourcesAvailable": "Extracurricular Program Sponsorship, Art and Music Supplies, Library Resources, Technology Access, Guest Lectures and Workshops",
    "contactName": "Contact 1594",
    "contactEmail": "contact5555@partner.com",
    "contactPhone": "883-786-7808",
    "addressStreet": "4423 Main St",
    "addressCity": "City 828",
    "addressState": "CA",
    "addressZipCode": "32515",
    "website": "http://www.partner2334.com",
    "description": "Description of Partner 1726",
    "partnershipStatus": "1"
  },
  {
    "partnerName": "Partner 3777",
    "organizationType": "NGO",
    "resourcesAvailable": "Mentorship Programs",
    "contactName": "Contact 3459",
    "contactEmail": "contact4442@partner.com",
    "contactPhone": "557-561-7773",
    "addressStreet": "8815 Main St",
    "addressCity": "City 927",
    "addressState": "PA",
    "addressZipCode": "26067",
    "website": "http://www.partner1483.com",
    "description": "Description of Partner 3808",
    "partnershipStatus": "1"
  },
  {
    "partnerName": "Partner 7161",
    "organizationType": "NGO",
    "resourcesAvailable": "Sports Equipment and Facilities",
    "contactName": "Contact 6224",
    "contactEmail": "contact854@partner.com",
    "contactPhone": "493-417-1044",
    "addressStreet": "8809 Main St",
    "addressCity": "City 830",
    "addressState": "PA",
    "addressZipCode": "51050",
    "website": "http://www.partner3907.com",
    "description": "Description of Partner 1251",
    "partnershipStatus": "1"
  },
  {
    "partnerName": "Partner 7083",
    "organizationType": "NGO",
    "resourcesAvailable": "Art and Music Supplies, Science and Lab Equipment, Extracurricular Program Sponsorship, Scholarships and Grants, Technology Access",
    "contactName": "Contact 4479",
    "contactEmail": "contact3157@partner.com",
    "contactPhone": "566-222-9044",
    "addressStreet": "6651 Main St",
    "addressCity": "City 130",
    "addressState": "VA",
    "addressZipCode": "25426",
    "website": "http://www.partner2085.com",
    "description": "Description of Partner 580",
    "partnershipStatus": "1"
  },
  {
    "partnerName": "Partner 1454",
    "organizationType": "Startup",
    "resourcesAvailable": "Technology Access, Art and Music Supplies, Library Resources",
    "contactName": "Contact 4066",
    "contactEmail": "contact9413@partner.com",
    "contactPhone": "513-985-6849",
    "addressStreet": "9478 Main St",
    "addressCity": "City 552",
    "addressState": "FL",
    "addressZipCode": "56958",
    "website": "http://www.partner4481.com",
    "description": "Description of Partner 7094",
    "partnershipStatus": "1"
  },
  {
    "partnerName": "Partner 6781",
    "organizationType": "Government Agency",
    "resourcesAvailable": "Scholarships and Grants",
    "contactName": "Contact 8950",
    "contactEmail": "contact4402@partner.com",
    "contactPhone": "929-776-1072",
    "addressStreet": "8344 Main St",
    "addressCity": "City 337",
    "addressState": "NY",
    "addressZipCode": "54791",
    "website": "http://www.partner6754.com",
    "description": "Description of Partner 2792",
    "partnershipStatus": "1"
  },
  {
    "partnerName": "Partner 5349",
    "organizationType": "Government Agency",
    "resourcesAvailable": "Technology Access, Library Resources, Mentorship Programs, Science and Lab Equipment, Extracurricular Program Sponsorship",
    "contactName": "Contact 3997",
    "contactEmail": "contact2888@partner.com",
    "contactPhone": "122-119-8888",
    "addressStreet": "3505 Main St",
    "addressCity": "City 506",
    "addressState": "NY",
    "addressZipCode": "16118",
    "website": "http://www.partner2753.com",
    "description": "Description of Partner 2854",
    "partnershipStatus": "1"
  },
  {
    "partnerName": "Partner 3735",
    "organizationType": "Corporation",
    "resourcesAvailable": "Scholarships and Grants, Internship Opportunities",
    "contactName": "Contact 6808",
    "contactEmail": "contact8763@partner.com",
    "contactPhone": "764-300-1641",
    "addressStreet": "9568 Main St",
    "addressCity": "City 665",
    "addressState": "OH",
    "addressZipCode": "69448",
    "website": "http://www.partner5622.com",
    "description": "Description of Partner 144",
    "partnershipStatus": "1"
  },
  {
    "partnerName": "Partner 2684",
    "organizationType": "Non-Profit",
    "resourcesAvailable": "Mentorship Programs, Scholarships and Grants, Science and Lab Equipment, Sports Equipment and Facilities",
    "contactName": "Contact 7635",
    "contactEmail": "contact9325@partner.com",
    "contactPhone": "302-954-7027",
    "addressStreet": "2460 Main St",
    "addressCity": "City 240",
    "addressState": "CA",
    "addressZipCode": "13025",
    "website": "http://www.partner8263.com",
    "description": "Description of Partner 5506",
    "partnershipStatus": "In1"
  },
  {
    "partnerName": "Partner 8365",
    "organizationType": "Startup",
    "resourcesAvailable": "Library Resources",
    "contactName": "Contact 4954",
    "contactEmail": "contact9416@partner.com",
    "contactPhone": "425-721-9578",
    "addressStreet": "7922 Main St",
    "addressCity": "City 325",
    "addressState": "CA",
    "addressZipCode": "83914",
    "website": "http://www.partner9398.com",
    "description": "Description of Partner 9407",
    "partnershipStatus": "1"
  },
  {
    "partnerName": "Partner 2514",
    "organizationType": "Government Agency",
    "resourcesAvailable": "Science and Lab Equipment",
    "contactName": "Contact 3401",
    "contactEmail": "contact8963@partner.com",
    "contactPhone": "943-612-1207",
    "addressStreet": "5721 Main St",
    "addressCity": "City 20",
    "addressState": "OH",
    "addressZipCode": "80759",
    "website": "http://www.partner1062.com",
    "description": "Description of Partner 1832",
    "partnershipStatus": "In1"
  },
  {
    "partnerName": "Partner 777",
    "organizationType": "Educational Institution",
    "resourcesAvailable": "Library Resources, Mentorship Programs, Extracurricular Program Sponsorship, Internship Opportunities, Art and Music Supplies",
    "contactName": "Contact 9301",
    "contactEmail": "contact95@partner.com",
    "contactPhone": "634-292-1469",
    "addressStreet": "1597 Main St",
    "addressCity": "City 324",
    "addressState": "NY",
    "addressZipCode": "92789",
    "website": "http://www.partner1314.com",
    "description": "Description of Partner 7218",
    "partnershipStatus": "1"
  },
  {
    "partnerName": "Partner 6298",
    "organizationType": "Non-Profit",
    "resourcesAvailable": "Internship Opportunities",
    "contactName": "Contact 5321",
    "contactEmail": "contact7437@partner.com",
    "contactPhone": "979-233-3800",
    "addressStreet": "7278 Main St",
    "addressCity": "City 977",
    "addressState": "OH",
    "addressZipCode": "74142",
    "website": "http://www.partner1374.com",
    "description": "Description of Partner 1818",
    "partnershipStatus": "1"
  },
  {
    "partnerName": "Partner 979",
    "organizationType": "Corporation",
    "resourcesAvailable": "Extracurricular Program Sponsorship",
    "contactName": "Contact 4495",
    "contactEmail": "contact6399@partner.com",
    "contactPhone": "663-882-6894",
    "addressStreet": "9740 Main St",
    "addressCity": "City 82",
    "addressState": "PA",
    "addressZipCode": "75804",
    "website": "http://www.partner276.com",
    "description": "Description of Partner 1575",
    "partnershipStatus": "1"
  },
  {
    "partnerName": "Partner 3064",
    "organizationType": "Corporation",
    "resourcesAvailable": "Art and Music Supplies",
    "contactName": "Contact 2227",
    "contactEmail": "contact9026@partner.com",
    "contactPhone": "737-636-1499",
    "addressStreet": "4659 Main St",
    "addressCity": "City 633",
    "addressState": "FL",
    "addressZipCode": "49805",
    "website": "http://www.partner9917.com",
    "description": "Description of Partner 8816",
    "partnershipStatus": "1"
  },
  {
    "partnerName": "Partner 8076",
    "organizationType": "Non-Profit",
    "resourcesAvailable": "Science and Lab Equipment",
    "contactName": "Contact 9241",
    "contactEmail": "contact4889@partner.com",
    "contactPhone": "373-885-8577",
    "addressStreet": "5492 Main St",
    "addressCity": "City 82",
    "addressState": "PA",
    "addressZipCode": "58569",
    "website": "http://www.partner8353.com",
    "description": "Description of Partner 1073",
    "partnershipStatus": "In1"
  },
  {
    "partnerName": "Partner 2220",
    "organizationType": "Educational Institution",
    "resourcesAvailable": "Mentorship Programs, Art and Music Supplies",
    "contactName": "Contact 4508",
    "contactEmail": "contact4167@partner.com",
    "contactPhone": "860-151-1996",
    "addressStreet": "3648 Main St",
    "addressCity": "City 534",
    "addressState": "MA",
    "addressZipCode": "92930",
    "website": "http://www.partner7942.com",
    "description": "Description of Partner 9297",
    "partnershipStatus": "In1"
  },
  {
    "partnerName": "Partner 5252",
    "organizationType": "Startup",
    "resourcesAvailable": "Technology Access, Art and Music Supplies, Library Resources, Guest Lectures and Workshops, Extracurricular Program Sponsorship",
    "contactName": "Contact 5611",
    "contactEmail": "contact4914@partner.com",
    "contactPhone": "658-872-5385",
    "addressStreet": "3374 Main St",
    "addressCity": "City 87",
    "addressState": "FL",
    "addressZipCode": "79104",
    "website": "http://www.partner5883.com",
    "description": "Description of Partner 2468",
    "partnershipStatus": "In1"
  },
  {
    "partnerName": "Partner 3404",
    "organizationType": "Corporation",
    "resourcesAvailable": "Mentorship Programs, Internship Opportunities",
    "contactName": "Contact 1444",
    "contactEmail": "contact7951@partner.com",
    "contactPhone": "788-725-2482",
    "addressStreet": "1202 Main St",
    "addressCity": "City 848",
    "addressState": "NY",
    "addressZipCode": "88864",
    "website": "http://www.partner7078.com",
    "description": "Description of Partner 2169",
    "partnershipStatus": "1"
  },
  {
    "partnerName": "Partner 4720",
    "organizationType": "NGO",
    "resourcesAvailable": "Art and Music Supplies, Guest Lectures and Workshops, Extracurricular Program Sponsorship, Sports Equipment and Facilities, Internship Opportunities",
    "contactName": "Contact 2451",
    "contactEmail": "contact9115@partner.com",
    "contactPhone": "253-688-5347",
    "addressStreet": "3901 Main St",
    "addressCity": "City 384",
    "addressState": "MA",
    "addressZipCode": "83924",
    "website": "http://www.partner8423.com",
    "description": "Description of Partner 6896",
    "partnershipStatus": "1"
  },
  {
    "partnerName": "Partner 2016",
    "organizationType": "Government Agency",
    "resourcesAvailable": "Science and Lab Equipment, Mentorship Programs, Library Resources",
    "contactName": "Contact 2347",
    "contactEmail": "contact9689@partner.com",
    "contactPhone": "470-795-1174",
    "addressStreet": "9854 Main St",
    "addressCity": "City 832",
    "addressState": "VA",
    "addressZipCode": "13396",
    "website": "http://www.partner6527.com",
    "description": "Description of Partner 3886",
    "partnershipStatus": "In1"
  },
  {
    "partnerName": "Partner 6601",
    "organizationType": "Government Agency",
    "resourcesAvailable": "Internship Opportunities, Art and Music Supplies, Sports Equipment and Facilities, Extracurricular Program Sponsorship, Technology Access",
    "contactName": "Contact 9032",
    "contactEmail": "contact7907@partner.com",
    "contactPhone": "801-761-6490",
    "addressStreet": "4708 Main St",
    "addressCity": "City 535",
    "addressState": "OH",
    "addressZipCode": "65933",
    "website": "http://www.partner3758.com",
    "description": "Description of Partner 9938",
    "partnershipStatus": "1"
  }
]